package za.ac.cputdigitalcard.domain;

import jakarta.persistence.*;

@Entity
public class Card {
    // Id Autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "cardId", unique = true, nullable = false)
    private Long cardId;
    @Column(name = "title", nullable = false)
    private String title;
    @Column(name = "initials", nullable = false)
    private String initials;
    @Column(name = "surname", nullable = false)
    private String surname;
    @Column(name = "course", nullable = false)
    private String course;
    @Column(name = "studentId", nullable = false)
    private Long studentId;
    private String date;
    @Lob
    private byte[] photo;
    @Lob
    private byte[] qrCode;

    protected Card() {
    }

    public Card(Builder builder) {
        this.cardId = builder.cardId;
        this.title = builder.title;
        this.initials = builder.initials;
        this.surname = builder.surname;
        this.course = builder.course;
        this.studentId = builder.studentId;
        this.date = builder.date;
        this.photo = builder.photo;
        this.qrCode = builder.photo;
    }

    // Getters
    public Long getCardId() {
        return cardId;
    }
    public String getTitle() {
        return title;
    }
    public String getInitials() {
        return initials;
    }
    public String getSurname() {
        return surname;
    }
    public String getCourse() {
        return course;
    }
    public Long getStudentId() {
        return studentId;
    }
    public String getDate() {
        return date;
    }
    public byte[] getPhoto() {
        return photo;
    }
    public byte[] getQrCode() {
        return qrCode;
    }

    // ToString method
    @Override
    public String toString() {
        return "Card{" +
                "cardId=" + cardId +
                ", title='" + title + '\'' +
                ", initials='" + initials + '\'' +
                ", surname='" + surname + '\'' +
                ", course='" + course + '\'' +
                ", date='" + date + '\'' +
                ", studentId=" + studentId +
                ", photo=" + photo  +
                ", qrCode=" + qrCode +
                '}';
    }

    // Builder Class
    public static class Builder {
        private Long cardId;
        private String title;
        private String initials;
        private String surname;
        private String course;
        private Long studentId;
        private String date;
        private byte[] photo;
        private byte[] qrCode;

        public Builder setCardId(Long cardId) {
            this.cardId = cardId;
            return this;
        }

        public Builder setTitle(String title) {
            this.title = title;
            return this;
        }

        public Builder setInitials(String initials) {
            this.initials = initials;
            return this;
        }

        public Builder setSurname(String surname) {
            this.surname = surname;
            return this;
        }

        public Builder setCourse(String course) {
            this.course = course;
            return this;
        }

        public Builder setStudentId(Long studentId) {
            this.studentId = studentId;
            return this;
        }

        public Builder setDate(String date) {
            this.date = date;
            return this;
        }

        public Builder setPhoto(byte[] photo) {
            this.photo = photo;
            return this;
        }
        public Builder setQrCode(byte[] qrCode) {
            this.qrCode = qrCode;
            return this;
        }

        // Builder copy method
        public Builder copy(Card card) {
            this.cardId = card.cardId;
            this.title = card.title;
            this.initials = card.initials;
            this.surname = card.surname;
            this.course = card.course;
            this.studentId = card.studentId;
            this.date = card.date;
            this.photo = card.photo;
            return this;
        }
        public Card build() {
            return new Card(this);
        }
    }
}
